package be.cetic.redirnet.impl;

import be.cetic.redirnet.*;


import java.net.URI;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: GEOGRAPHIC_POINT <br>
 * @version generated on Fri Feb 16 14:36:20 CET 2018 by nm
 */
import javax.xml.bind.annotation.XmlRootElement;
 
@XmlRootElement
public class GEOGRAPHIC_POINT {


     String id;

     public String getId() {
         return this.id;
     }

     public void setId(String id) {
         this.id=id;
     }


}
