package be.cetic.redirnet.impl;

import be.cetic.redirnet.*;


import java.net.URI;

/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: Resource <br>
 * @version generated on Fri Feb 16 14:36:20 CET 2018 by nm
 */
import javax.xml.bind.annotation.XmlRootElement;
 
@XmlRootElement
public class Resource {

     String id;

     public String getId() {
         return this.id;
     }

     public void setId(String id) {
         this.id=id;
     }



    /* ***************************************************
     * Object Property http://www.semanticweb.org/ontologies/2015/0/redirnet-core-ontology/administeredBy
     */
    Station administeredBy;
     
    public Station getAdministeredBy() {
        return this.administeredBy;
    }

    public void setAdministeredBy(Station newAdministeredBy) {
        this.administeredBy= newAdministeredBy;
    }

    /* ***************************************************
     * Object Property http://www.semanticweb.org/ontologies/2015/0/redirnet-core-ontology/deployedAt
     */
     
    Event deployedAt;

    public Event getDeployedAt() {
        return deployedAt;
    }

    public void setDeployedAt(Event newDeployedAt) {
        this.deployedAt= newDeployedAt;
    }

    /* ***************************************************
     * Object Property http://www.semanticweb.org/ontologies/2015/0/redirnet-core-ontology/operatedBy
     */

    Agency operatedBy;
     
    public Agency getOperatedBy() {
	   return this.operatedBy;
    }

    public void setOperatedBy(Agency newOperatedBy) {
	   this.operatedBy= newOperatedBy;
    }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/ontologies/2015/0/redirnet-core-ontology/resourceLocation
     */
     
    LOCATION resourceLocation;

    public LOCATION getResourceLocation() {
        return this.resourceLocation;
    }


    public void setResourceLocation(LOCATION newResourceLocation) {
        this.resourceLocation= newResourceLocation;
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/ontologies/2015/0/redirnet-core-ontology/resourceCode
     */
     
    String resourceCode;

    public String getResourceCode() {
		return this.resourceCode;
    }

    public void setResourceCode(String newResourceCode) {
		this.resourceCode=newResourceCode;
    }

    /* ***************************************************
     * Data Property http://www.semanticweb.org/ontologies/2015/0/redirnet-core-ontology/resourceStatus
     */
     
    String resourceStatus;

    public String getResourceStatus() {
		return this.resourceStatus;
    }

    public void setResourceStatus(String newResourceStatus) {
		this.resourceStatus=newResourceStatus;
    }

}
