package be.cetic.redirnet.impl;

import be.cetic.redirnet.*;


import java.net.URI;

/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultStation <br>
 * @version generated on Fri Feb 16 14:36:20 CET 2018 by nm
 */
import javax.xml.bind.annotation.XmlRootElement;
 
@XmlRootElement
public class Station{


     String id;

     public String getId() {
         return this.id;
     }

     public void setId(String id) {
         this.id=id;
     }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/ontologies/2015/0/redirnet-core-ontology/administratorOf
     */
    Resource administratorOf;
     
    public Resource getAdministratorOf() {
        return  this.administratorOf;
    }

    public void setAdministratorOf(Resource newAdministratorOf) {
        this.administratorOf= newAdministratorOf;
    }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/ontologies/2015/0/redirnet-core-ontology/divisionOf
     */

    Agency divisionOf;

    public Agency getDivisionOf() {
        return this.divisionOf;
    }

    public void setDivisionOf(Agency newDivisionOf) {
        this.divisionOf=newDivisionOf;
    }



    /* ***************************************************
     * Object Property http://www.semanticweb.org/ontologies/2015/0/redirnet-core-ontology/stationLocation
     */
     
	LOCATION stationLocation;
    public LOCATION getStationLocation() {
	   return this.stationLocation;
    }
    public void setStationLocation(LOCATION newStationLocation) {
	   this.stationLocation= newStationLocation;
    }

}
