package be.cetic.ors.ontologybinding.pojo;

import javax.xml.bind.annotation.XmlRootElement;
/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultTecLocation <br>
 * @version generated on Fri Sep 08 15:44:47 CEST 2017 by nm
 */
 
@XmlRootElement
public class Location {

    String id;
    public String getId() {
        return id;
    }


    public void setId(String newId) {
        this.id=newId;
    }




    String longitude;
    public String getLongitude() {
		return longitude;
    }

    public void setLongitude(String x) {
		this.longitude=x;
    }

    String latitude;
    public String getLatitude() {
		return latitude;
    }

    public void setLatitude(String x) {
		this.latitude=x;
    }

    String street_address;
    public String getStreet_address() {
		return street_address;
    }

    public void setStreet_address(String newStreetname) {
		this.street_address= newStreetname;
    }

    String location_name;
    public String getLocation_name() {
		return location_name;
    }

    public void setLocation_name(String newStreetname) {
		this.location_name= newStreetname;
    }


}
