package be.cetic.ors.ontologybinding.pojo;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultTecStop <br>
 * @version generated on Fri Sep 08 15:44:47 CEST 2017 by nm
 */
@XmlRootElement
public class POI {



    /* ***************************************************
     * Object Property http://www.semanticweb.org/nm/ontologies/2017/6/TECSTP#stop_location
     */
    Location poi_location; 
    public Location getPoi_location() {
        return poi_location;
    }


    public void setPoi_location(Location loc) {
        this.poi_location=loc;
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/nm/ontologies/2017/6/mobits-lite#idstop
     */

    String id; 
    public String getId() {
		return id;
    }


    public void setId(String newId) {
        this.id=newId;
    }

}
