package be.cetic.ors.ontologybinding.pojo;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultTecStop <br>
 * @version generated on Fri Sep 08 15:44:47 CEST 2017 by nm
 */
@XmlRootElement
public class Stop extends POI{




    /* ***************************************************
     * Data Property http://www.semanticweb.org/nm/ontologies/2017/6/mobits-lite#stop_description
     */
     
    String stop_description; 
    public String getStop_description() {
		return this.stop_description;
    }

    public void setStop_description(String newDescription) {
        this.stop_description=newDescription;
    }



    /* ***************************************************
     * Data Property http://www.semanticweb.org/nm/ontologies/2017/6/mobits-lite#idstop
     */

    String id; 
    public String getId() {
		return id;
    }


    public void setId(String newId) {
        this.id=newId;
    }

}
