package be.cetic.ors.ontologybinding.pojo;

import javax.xml.bind.annotation.XmlRootElement;
/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultTecLocation <br>
 * @version generated on Fri Sep 08 15:44:47 CEST 2017 by nm
 */
 
@XmlRootElement
public class TecLocation {

    String id;
    public String getId() {
        return id;
    }


    public void setId(String newId) {
        this.id=newId;
    }





    /* ***************************************************
     * Data Property http://www.semanticweb.org/nm/ontologies/2017/6/TECSTP#X_coordinate
     */
     
    int X_coordinate;
    public int getX_coordinate() {
		return X_coordinate;
    }

    public void setX_coordinate(int X) {
		this.X_coordinate=X;
    }

    /* ***************************************************
     * Data Property http://www.semanticweb.org/nm/ontologies/2017/6/TECSTP#Y_coordinate
     */
     
    int Y_coordinate;
    public int getY_coordinate() {
		return Y_coordinate;
    }

    public void setY_coordinate(int Y) {
		this.Y_coordinate=Y;
    }

    /* ***************************************************
     * Data Property http://www.semanticweb.org/nm/ontologies/2017/6/TECSTP#country_abv
     */
     
    String country_abv;
    public String getCountry_abv() {
		return country_abv;
    }

    public void setCountry_abv(String abv) {
		this.country_abv=abv;
    }

    /* ***************************************************
     * Data Property http://www.semanticweb.org/nm/ontologies/2017/6/TECSTP#municipality_fr
     */
     
	String municipality_fr;
    public String  getMunicipality_fr() {
		return municipality_fr;
    }

    public void setMunicipality_fr(String newMunicipality_fr) {
        this.municipality_fr=newMunicipality_fr;
    }
    /* ***************************************************
     * Data Property http://www.semanticweb.org/nm/ontologies/2017/6/TECSTP#municipality_nl
     */
	String municipality_nl;
    public String  getMunicipality_nl() {
		return municipality_nl;
    }
     
    public void setMunicipality_nl(String newMunicipality_nl) {
        this.municipality_nl=newMunicipality_nl;
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/nm/ontologies/2017/6/TECSTP#streetname_fr
     */
    String streetname_fr;
    public String getStreetname_fr() {
		return streetname_fr;
    }

    public void setStreetname_fr(String newStreetname_fr) {
		this.streetname_fr= newStreetname_fr;
    }


    /* ***************************************************
     * Data Property http://www.semanticweb.org/nm/ontologies/2017/6/TECSTP#streetname_nl
     */
     
    String streetname_nl;
    public String getStreetname_nl() {
		return streetname_nl;
    }

    public void setStreetname_nl(String newStreetname_nl) {
		this.streetname_nl= newStreetname_nl;
    }

}
